### PR TITLE
Test with earth engine layer

### PR DESCRIPTION
**Pull request by fsn1995**
1. Edited Provider module and added a function to display tile layer generated from Google Earth Engine.
2. Created a jupyter notebook with 3 map samples:
- Night light trends
- MODIS NDVI
- MODIS Snow Albedo 

You must have already registered at Google Earth Engine in order to reproduce the notebook result.

### CODE REVIEW

**Comment by rafaqz** [comment]
Thanks!!

It would be cool to gnerate the tile layer URLs based on the standard name strings for the earth engine layers, like: 

```julia
EarthEngine(; map_name="LANDSAT/LT05/C01/T1_SR/LT05_034033_20000913")
```

I'm just wondering how we can do that cleanly. The ee api seems to have a really simple url building sceme:
```javascript
 url_format = '%s/%s/%s/tiles/{z}/{x}/{y}' % (
      _tile_base_url, _cloud_api_utils.VERSION, map_name)
  if _cloud_api_key:
    url_format += '?key=%s' % _cloud_api_key
```

https://github.com/google/earthengine-api/blob/fbf409381c7921db7a3a0d6aba404474a4fe1f3c/python/ee/data.py#L577-L580

where:
```javascript
DEFAULT_TILE_BASE_URL = 'https://earthengine.googleapis.com'
```
So:
```julia
function EarthEnv(; url=nothing, map_name="Some/default/map_name", cloud_api_key=nothing, version="some_default_version")
    url = if isnothing(url)
        joinpath(DEFAULT_TILE_BASE_URL, version, map_name)
    else
        url
    end
    
    if !isnothing(cloud_api_key)
        url = url * "?key=" * cloud_api_key
    end
    # make the Dict using `url`
    ...
end
```

What do you think? My reasoning is that EarthEngine.jl is kind of heavy to use and the pip/python setup is a little painful if we could just get urls either by generating them or by using the javascript api. 

Of course for your use case you would use EarthEngine.jl! But if we can get something basic "just working" from the name that would be awesome.

Maybe getting the right version is a little complicated...

**Comment by fsn1995** [comment]
Yes that would be cool. The problem is all map tiles generated are not permanent. 
I have never really looked into it but I think the image id is like a folder path to google cloud storage bucket (e.g. https://cloud.google.com/storage/docs/public-datasets/landsat). GEE will generate a new map IDs/URL every time we request it like( `Map.addLayer(image, visParams, "layer name")`).
In summary, the same image id will have a unique map IDs/URL or map_name every time we call earth engine. 

So far I think the getmapid is the best option. https://developers.google.com/earth-engine/apidocs/ee-data-getmapid?hl=en

**Comment by fsn1995** [comment]
Was trying to do something like this, but the getMapId is from earthengine python api. Any suggestions? 
```julia
function EarthEngineMap(eeObject, visParams::Dict)
    map_id_dict = ee.Image(eeObject).getMapId(visParams)
    map_url = map_id_dict["tile_fetcher"].url_format
    provider = LeafletProvider(
        map_url,
        Dict{Symbol,Any}(
            :maxZoom => 20,
            :attribution => """&copy; <a href="https://earthengine.google.com/terms/">Google Earth Engine</a>"""
        )
    )
    return provider
end
```

**Comment by rafaqz** [comment]
Thanks, I'm finally getting around to updating this.

**Pull request merged**
